# Safe EDR Agent Configuration
# This configuration is designed to prevent system freezes and minimize system impact

server:
  url: "http://192.168.20.85:5000"
  api_key: "f93ac1d1d7b64f07bd32c81e6ab8423e4cb7631f2051c9d8a2d340c5be3a4a9e"
  auth_token: "edr_system_auth_2025"
  timeout: 30
  retry_count: 2
  tls_verify: false

agent:
  id: ""
  name: "edr-agent-windows-safe"
<<<<<<< HEAD
  heartbeat_interval: 60     # Send heartbeats more frequently
  event_batch_size: 100      # Moderate batch size for timely delivery
  max_queue_size: 1000       # Allow more events before backpressure

monitoring:
  file_system:
    enabled: true
    paths:                    # Use concrete paths that actually exist
      - "C:\\Users\\Manh\\Desktop"
      - "C:\\Users\\Manh\\Downloads"
      - "C:\\Users\\Manh\\Documents"
    recursive: true
    real_time_scan: true
    max_file_size: "10MB"     # Reduced file size limit
    max_workers: 5            # Increased worker limit to handle all directories
=======
  heartbeat_interval: 300    # Increased to reduce server traffic
  event_batch_size: 50       # Reduced batch size
  max_queue_size: 500        # Reduced queue size to prevent memory issues

monitoring:
  file_system:
    enabled: false            # Disabled by default for safety
    paths: []                 # Empty paths to prevent system monitoring
    recursive: false
    real_time_scan: false
    max_file_size: "10MB"     # Reduced file size limit
>>>>>>> 00e9527bf4c697277e34f52d96c010daf1e280ef
    exclude_extensions:
      - ".tmp"
      - ".log"
      - ".bak"
      - ".cache"
      - ".db"
      - ".sqlite"
      - ".etl"
      - ".evtx"
      - ".lock"
      - ".crdownload"
      - ".partial"
    exclude_paths:
      - "C:\\Windows\\*"
      - "C:\\Program Files\\*"
      - "C:\\Program Files (x86)\\*"
      - "C:\\ProgramData\\Microsoft\\Windows Defender\\*"
      - "C:\\Users\\*\\AppData\\Local\\Temp\\*"
      - "C:\\$Recycle.Bin\\*"
      - "C:\\System Volume Information\\*"
      - "C:\\Recovery\\*"
      - "*\\quarantine\\*"

  processes:
    enabled: false            # Disabled by default for safety
    scan_executables: false
    monitor_injections: false
    track_network_connections: false
    monitor_cmdline: false
    exclude_names:
      - "System"
      - "Idle"
      - "Registry"
      - "smss.exe"
      - "csrss.exe"
      - "wininit.exe"
      - "services.exe"
      - "lsass.exe"
      - "winlogon.exe"
      - "svchost.exe"
      - "dwm.exe"
      - "explorer.exe"
      - "taskmgr.exe"
      - "audiodg.exe"
      - "conhost.exe"
      - "fontdrvhost.exe"

  network:
<<<<<<< HEAD
    enabled: true
    monitor_dns: true
    block_malicious_ips: true
    capture_packets: false      # keep off to avoid heavy load
    monitor_tcp: true
    monitor_udp: true
    scan_interval: 120

  registry:
    enabled: true
    monitor_autostart: true
    track_security_settings: true
    scan_interval: 300

  memory:
    enabled: true
=======
    enabled: false            # Disabled to reduce system load
    monitor_dns: false
    block_malicious_ips: false
    capture_packets: false
    monitor_tcp: false
    monitor_udp: false
    scan_interval: 300

  registry:
    enabled: false            # Disabled to reduce noise
    monitor_autostart: false
    track_security_settings: false
    scan_interval: 600

  memory:
    enabled: false            # Disabled to prevent system impact
>>>>>>> 00e9527bf4c697277e34f52d96c010daf1e280ef
    scan_interval: 1800
    threat_threshold: 0.9
    max_processes: 5

  behavior:
<<<<<<< HEAD
    enabled: true
    analysis_interval: 300
=======
    enabled: false            # Disabled to reduce system impact
    analysis_interval: 600
>>>>>>> 00e9527bf4c697277e34f52d96c010daf1e280ef
    threat_threshold: 0.9
    data_retention: 2

yara:
<<<<<<< HEAD
  enabled: true
  rules_path: "yara-rules"
  yara_executable: "yara64.exe"  # Specify the YARA executable path
  categories:
    - "maldocs"
    - "malware"
    - "webshells"
    - "exploit_kits"
    - "backdoor"
    - "trojan"
    - "ransomware"
  scan_timeout: 30          # seconds
  max_file_size: "100MB"
=======
  enabled: false              # Disabled by default for safety
  auto_update: false
  update_interval: "24h"
  rules_source: ""
  categories: []
  max_scan_threads: 1         # Single thread to prevent overload
  scan_timeout: 10            # Reduced timeout
  rules_path: "yara-rules"
  max_file_size: "10MB"       # Reduced file size limit
>>>>>>> 00e9527bf4c697277e34f52d96c010daf1e280ef

response:
  notification_settings:
    toast_enabled: true
<<<<<<< HEAD
    system_tray_enabled: false
    desktop_alert_enabled: true
    sound_enabled: false
    timeout_seconds: 6
  severity_thresholds:
    show_user_alerts: 3     # show alerts for Medium+
    auto_quarantine: 4      # auto quarantine High/ Critical
    block_execution: 5      # block only on Critical
  user_interaction:
    allow_user_override: false
    require_admin_for_allow: true
    timeout_seconds: 20
=======
    system_tray_enabled: true
    desktop_alert_enabled: false  # Disabled to prevent UI freezes
    sound_enabled: false
    timeout_seconds: 5

  severity_thresholds:
    show_user_alerts: 5         # Only show critical alerts
    auto_quarantine: 6          # Disabled (no auto-quarantine)
    block_execution: 6          # Disabled (no auto-blocking)

  user_interaction:
    allow_user_override: true
    require_admin_for_allow: false
    timeout_seconds: 15

>>>>>>> 00e9527bf4c697277e34f52d96c010daf1e280ef
  customization:
    company_branding: false
    custom_messages: false
    language: "en"

logging:
  level: "info"
  format: "text"
  file_path: "agent.log"
  max_size: "10MB"
  max_files: 2
  compress: true

# Performance tuning to prevent system overload
performance:
  max_memory_usage: "128MB"      # Reduced memory limit
  cpu_limit_percent: 10         # Reduced CPU usage limit
  scan_queue_size: 20           # Reduced queue size
  event_queue_size: 100         # Reduced event queue
  cleanup_interval: 1800        # Cleanup every 30 minutes

# Enhanced suppression rules to prevent noise
suppression:
  rules:
    - type: "path_contains"
      values: 
        - "\\Windows\\"
        - "\\Program Files\\"
        - "\\Program Files (x86)\\"
        - "\\ProgramData\\Microsoft\\Windows Defender\\"
        - "\\$Recycle.Bin\\"
        - "\\System Volume Information\\"
        - "\\Recovery\\"
        - "\\quarantine\\"
        - "\\edr-agent"
      reason: "system_path"
      
    - type: "rule_name_contains"
      values:
        - "powershell"
        - "debuggercheck"
        - "vmdetect"
        - "anti_dbg"
        - "capabilities"
        - "environmental"
      reason: "environmental_detection"
      
    - type: "file_extension"
      values:
        - ".tmp"
        - ".log"
        - ".bak" 
        - ".cache"
        - ".db"
        - ".sqlite"
        - ".lock"
      reason: "temporary_file"

# Safe mode settings
safe_mode:
<<<<<<< HEAD
  enabled: false
  max_file_monitors: 5
  max_process_monitors: 3
  disable_real_time: false
  reduce_scanning: false
  minimal_logging: false
=======
  enabled: true
  max_file_monitors: 1
  max_process_monitors: 1
  disable_real_time: true
  reduce_scanning: true
  minimal_logging: true
>>>>>>> 00e9527bf4c697277e34f52d96c010daf1e280ef
