# EDR Agent Configuration for Windows
# Optimized for performance and security monitoring

server:
  url: "http://192.168.20.85:5000"
  api_key: "f93ac1d1d7b64f07bd32c81e6ab8423e4cb7631f2051c9d8a2d340c5be3a4a9e"
  auth_token: "edr_system_auth_2025"
  timeout: 30
  retry_count: 3
  tls_verify: false
  websocket_enabled: false

agent:
  id: ""
  name: "edr-agent-windows"
  heartbeat_interval: 60        # Send heartbeats every 60 seconds
  event_batch_size: 100         # Batch size for events
  max_queue_size: 2000          # Maximum events in queue

monitoring:
  file_system:
    enabled: true               # Enable file system monitoring
    paths:                      # Directories to monitor
      - "C:\\Users\\Manh\\Desktop"
      - "C:\\Users\\Manh\\Downloads"
      - "C:\\Users\\Manh\\Documents"
      - "C:\\Users\\Manh\\Pictures"
    recursive: true             # Monitor subdirectories
    real_time_scan: true        # Real-time file scanning
    max_file_size: "50MB"       # Maximum file size to scan
    max_workers: 8              # Number of worker threads
    exclude_extensions:         # File extensions to exclude
      - ".tmp"
      - ".log"
      - ".bak"
      - ".cache"
      - ".db"
      - ".sqlite"
      - ".etl"
      - ".evtx"
      - ".lock"
      - ".crdownload"
      - ".partial"
      - ".tmp"
    exclude_paths:              # Paths to exclude from monitoring
      - "C:\\Windows\\*"
      - "C:\\Program Files\\*"
      - "C:\\Program Files (x86)\\*"
      - "C:\\ProgramData\\Microsoft\\Windows Defender\\*"
      - "C:\\Users\\*\\AppData\\Local\\Temp\\*"
      - "C:\\$Recycle.Bin\\*"
      - "C:\\System Volume Information\\*"
      - "C:\\Recovery\\*"
      - "*\\quarantine\\*"
      - "*\\edr-agent\\*"

  processes:
    enabled: true               # Enable process monitoring
    scan_executables: true      # Scan executable files
    monitor_injections: true    # Monitor process injections
    track_network_connections: true  # Track network connections
    monitor_cmdline: true       # Monitor command line arguments
    exclude_names:              # Process names to exclude
      - "System"
      - "Idle"
      - "Registry"
      - "smss.exe"
      - "csrss.exe"
      - "wininit.exe"
      - "services.exe"
      - "lsass.exe"
      - "winlogon.exe"
      - "svchost.exe"
      - "dwm.exe"
      - "explorer.exe"
      - "taskmgr.exe"
      - "audiodg.exe"
      - "conhost.exe"
      - "fontdrvhost.exe"

  network:
    enabled: true               # Enable network monitoring
    monitor_dns: true           # Monitor DNS queries
    block_malicious_ips: true   # Block malicious IP addresses
    capture_packets: false      # Disable packet capture (performance)
    monitor_tcp: true           # Monitor TCP connections
    monitor_udp: true           # Monitor UDP connections
    scan_interval: 120          # Network scan interval (seconds)
    suspicious_ports:           # Ports to flag as suspicious
      - 22
      - 23
      - 3389
      - 5900
      - 8080
    exclude_ports:              # Ports to exclude
      - 80
      - 443
      - 53

  registry:
    enabled: true               # Enable registry monitoring
    monitor_autostart: true     # Monitor autostart entries
    track_security_settings: true  # Track security settings
    scan_interval: 300          # Registry scan interval (seconds)
    paths:                      # Registry paths to monitor
      - "HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run"
      - "HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\RunOnce"
      - "HKEY_CURRENT_USER\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run"
      - "HKEY_CURRENT_USER\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\RunOnce"

  memory:
    enabled: true               # Enable memory monitoring
    scan_interval: 1800         # Memory scan interval (seconds)
    threat_threshold: 0.8       # Threat detection threshold
    max_processes: 10           # Maximum processes to scan
    scan_executable: true       # Scan executable memory
    scan_writable: true         # Scan writable memory
    scan_private: true          # Scan private memory

  behavior:
    enabled: true               # Enable behavior analysis
    analysis_interval: 300      # Behavior analysis interval (seconds)
    threat_threshold: 0.8       # Threat detection threshold
    data_retention: 7           # Days to retain behavior data
    max_child_processes: 20     # Maximum child processes
    max_network_connections: 50 # Maximum network connections
    max_memory_operations: 1000 # Maximum memory operations
    max_file_operations: 500    # Maximum file operations
    max_file_access: 1000       # Maximum file access
    max_registry_access: 500    # Maximum registry access
    max_bytes_sent: 1048576     # Maximum bytes sent (1MB)
    max_bytes_received: 1048576 # Maximum bytes received (1MB)

yara:
  enabled: true                 # Enable YARA scanning
  rules_path: "yara-rules"      # Path to YARA rules
  yara_executable: "yara64.exe" # YARA executable path
  auto_update: true             # Auto-update rules
  update_interval: "24h"        # Update interval
  rules_source: ""              # Rules source URL
  categories:                   # YARA rule categories to load
    - "maldocs"
    - "malware"
    - "webshells"
    - "exploit_kits"
    - "backdoor"
    - "trojan"
    - "ransomware"
    - "antidebug_antivm"
    - "local"
  max_scan_threads: 4           # Maximum scan threads
  scan_timeout: 30              # Scan timeout (seconds)
  max_file_size: "100MB"        # Maximum file size to scan

response:
  notification_settings:
    toast_enabled: true         # Enable Windows toast notifications
    system_tray_enabled: true   # Enable system tray notifications
    desktop_alert_enabled: true # Enable desktop alerts
    sound_enabled: false        # Disable sound notifications
    timeout_seconds: 8          # Notification timeout

  severity_thresholds:
    show_user_alerts: 3         # Show alerts for Medium+ severity
    auto_quarantine: 4          # Auto-quarantine High/Critical threats
    block_execution: 5          # Block execution for Critical threats

  user_interaction:
    allow_user_override: true   # Allow user to override actions
    require_admin_for_allow: true  # Require admin for allow actions
    timeout_seconds: 30         # User interaction timeout

  customization:
    company_branding: false     # Disable company branding
    custom_messages: false      # Disable custom messages
    language: "en"              # Language

logging:
  level: "info"                 # Log level
  format: "text"                # Log format
  file_path: "agent.log"        # Log file path
  max_size: "20MB"              # Maximum log file size
  max_files: 5                  # Maximum log files
  compress: true                # Compress old logs

performance:
  max_memory_usage: "256MB"     # Maximum memory usage
  cpu_limit_percent: 25         # CPU usage limit
  scan_queue_size: 50           # Scan queue size
  event_queue_size: 500         # Event queue size
  cleanup_interval: 1800        # Cleanup interval (30 minutes)

suppression:
  rules:
    - type: "path_contains"
      values: 
        - "\\Windows\\"
        - "\\Program Files\\"
        - "\\Program Files (x86)\\"
        - "\\ProgramData\\Microsoft\\Windows Defender\\"
        - "\\$Recycle.Bin\\"
        - "\\System Volume Information\\"
        - "\\Recovery\\"
        - "\\quarantine\\"
        - "\\edr-agent"
      reason: "system_path"
      
    - type: "rule_name_contains"
      values:
        - "powershell"
        - "debuggercheck"
        - "vmdetect"
        - "anti_dbg"
        - "capabilities"
        - "environmental"
      reason: "environmental_detection"
      
    - type: "file_extension"
      values:
        - ".tmp"
        - ".log"
        - ".bak" 
        - ".cache"
        - ".db"
        - ".sqlite"
        - ".lock"
      reason: "temporary_file"

safe_mode:
  enabled: false                # Disable safe mode for full functionality
  max_file_monitors: 10         # Maximum file monitors
  max_process_monitors: 5       # Maximum process monitors
  disable_real_time: false      # Enable real-time monitoring
  reduce_scanning: false        # Full scanning capability
  minimal_logging: false        # Full logging capability
