server:
  url: "http://192.168.20.85:5000"
  api_key: ""  # Will be set during registration
  timeout: 30
  retry_count: 3
  tls_verify: false

agent:
  id: ""  # Will be generated during installation
  name: ""  # Will be set to hostname
  heartbeat_interval: 30
  event_batch_size: 100
  max_queue_size: 10000

monitor:
  files:
    enabled: true
    paths:
      - "C:\\Program Files"
      - "C:\\Program Files (x86)"
      - "C:\\Windows\\System32"
      - "C:\\Windows\\SysWOW64"
      - "C:\\Users"
    recursive: true
    scan_on_write: true
    max_file_size: "100MB"
    exclude_exts:
      - ".tmp"
      - ".log"
      - ".bak"
  
  processes:
    enabled: true
    scan_executable: true
    monitor_cmdline: true
    exclude_names:
      - "explorer.exe"
      - "dwm.exe"
      - "winlogon.exe"
  
  network:
    enabled: true
    monitor_tcp: true
    monitor_udp: false
    exclude_ports:
      - 135
      - 445
      - 5985
  
  registry:
    enabled: true
    keys:
      - "HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run"
      - "HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\RunOnce"
      - "HKCU\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run"

scanner:
  yara_enabled: true
  yara_rules_path: "yara-rules"
  max_scan_threads: 4
  scan_timeout: 30

log:
  level: "info"
  format: "json"
  file_path: "C:\\Program Files\\EDR-Agent\\logs\\agent.log"
  max_size: 100 