server:
  url: "http://192.168.20.85:5000"
  api_key: "f93ac1d1d7b64f07bd32c81e6ab8423e4cb7631f2051c9d8a2d340c5be3a4a9e"
  auth_token: "edr_system_auth_2025"
  timeout: 30
  retry_count: 3
  tls_verify: false

agent:
  id: ""
  name: "edr-agent-windows"
  heartbeat_interval: 120  # Increased to reduce server traffic
  event_batch_size: 50     # Reduced to send smaller batches more frequently
  max_queue_size: 5000     # Reduced to prevent excessive memory usage

monitoring:
  file_system:
    enabled: true
    paths:
      - "C:\\Users"
      - "C:\\Program Files"
      - "C:\\Program Files (x86)"
      - "C:\\Windows\\System32"
    recursive: true
    real_time_scan: true
    max_file_size: "50MB"   # Reduced to prevent scanning very large files
    exclude_extensions:
      - ".tmp"
      - ".log"
      - ".bak"
      - ".cache"
      - ".db"
      - ".sqlite"
      - ".etl"
      - ".evtx"

  processes:
    enabled: true
    scan_executables: true
    monitor_injections: true
    track_network_connections: true
    monitor_cmdline: true
    exclude_names:
      - "explorer.exe"
      - "dwm.exe"
      - "winlogon.exe"
      - "MoUsoCoreWorker.exe"
      - "taskhostw.exe"
      - "csrss.exe"
      - "lsass.exe"
      - "services.exe"
      - "wininit.exe"
      - "smss.exe"

  network:
    enabled: true
    monitor_dns: true
    block_malicious_ips: false
    capture_packets: false
    monitor_tcp: true
    monitor_udp: false
    scan_interval: 60       # Reduced frequency
    exclude_ports:
      - 135
      - 445
      - 5985
      - 3389
    suspicious_ports:
      - 22
      - 23
      - 5900
      - 8080
      - 4444
      - 1337

  registry:
    enabled: true
    monitor_autostart: true
    track_security_settings: true
    scan_interval: 60       # Reduced frequency
    paths:
      - "HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run"
      - "HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\RunOnce"
      - "HKCU\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run"

  memory:
    enabled: false          # Disabled to reduce noise
    scan_interval: 600
    threat_threshold: 0.7   # Increased threshold
    max_processes: 20       # Reduced scope

  behavior:
    enabled: false          # Disabled to reduce noise
    analysis_interval: 120
    threat_threshold: 0.8   # Increased threshold
    data_retention: 12      # Reduced retention

yara:
  enabled: true
  auto_update: false
  update_interval: "24h"
  rules_source: https://github.com/Yara-Rules/rules/archive/master.zip
  categories:              # Reduced to essential categories
    - malware
    - maldocs
    - webshells
  max_scan_threads: 2      # Reduced to lower system impact
  scan_timeout: 15         # Reduced timeout
  rules_path: yara-rules
  max_file_size: "50MB"    # Reduced max file size

response:
  notification_settings:
    toast_enabled: true
    system_tray_enabled: true
    desktop_alert_enabled: true
    sound_enabled: false     # Disabled to reduce noise
    timeout_seconds: 5       # Reduced timeout

  severity_thresholds:
    show_user_alerts: 3      # Only show medium+ alerts
    auto_quarantine: 4       # Only quarantine high+ severity
    block_execution: 5       # Only block critical threats

  user_interaction:
    allow_user_override: true
    require_admin_for_allow: true
    timeout_seconds: 30

  customization:
    company_branding: false
    custom_messages: false
    language: "en"

logging:
  level: "info"            # Reduced from debug to info
  format: "text"
  file_path: "agent.log"
  max_size: "10MB"