server:
  url: "http://192.168.20.85:5000"
  api_key: "f93ac1d1d7b64f07bd32c81e6ab8423e4cb7631f2051c9d8a2d340c5be3a4a9e"
  auth_token: "edr_system_auth_2025"
  timeout: 45        # Increased timeout to prevent server communication issues
  retry_count: 2     # Reduced retries to avoid log spam
  tls_verify: false

agent:
  id: ""
  name: "edr-agent-windows"
  heartbeat_interval: 180    # Increased to reduce server traffic
  event_batch_size: 100      # Increased batch size for efficiency
  max_queue_size: 2000       # Reduced to prevent memory issues

monitoring:
  file_system:
    enabled: true
    paths:
      - "C:\\Users"
      - "C:\\Program Files"
      - "C:\\Program Files (x86)"
      - "C:\\Windows\\System32"
    recursive: true
    real_time_scan: true
    max_file_size: "50MB"
    exclude_extensions:
      - ".tmp"
      - ".log"
      - ".bak"
      - ".cache"
      - ".db"
      - ".sqlite"
      - ".etl"
      - ".evtx"
      - ".go"           # Exclude Go source files
      - ".js"
      - ".ts"
      - ".json"
      - ".yaml"
      - ".yml"
      - ".md"
      - ".txt"
    exclude_paths:      # New: exclude specific paths
      - "C:\\Users\\Manh\\Desktop\\AgentWindows"
      - "C:\\Users\\*\\AppData\\Local\\Temp\\go-build"
      - "C:\\Windows\\Temp"
      - "*\\node_modules"
      - "*\\.git"
      - "*\\.vs"
      - "*\\.vscode"
      - "*\\cursor\\user\\workspacestorage"

  processes:
    enabled: true
    scan_executables: true
    monitor_injections: false    # Disabled to reduce noise
    track_network_connections: false  # Disabled to reduce noise
    monitor_cmdline: true
    exclude_names:
      - "explorer.exe"
      - "dwm.exe"
      - "winlogon.exe"
      - "MoUsoCoreWorker.exe"
      - "taskhostw.exe"
      - "csrss.exe"
      - "lsass.exe"
      - "services.exe"
      - "wininit.exe"
      - "smss.exe"
      - "SearchIndexer.exe"
      - "SearchProtocolHost.exe"
      - "RuntimeBroker.exe"
      - "ApplicationFrameHost.exe"

  network:
    enabled: false     # Disabled to reduce system load and noise
    monitor_dns: false
    block_malicious_ips: false
    capture_packets: false
    monitor_tcp: false
    monitor_udp: false
    scan_interval: 120
    exclude_ports:
      - 135
      - 445
      - 5985
      - 3389
      - 80
      - 443
      - 53
    suspicious_ports:
      - 22
      - 23
      - 5900
      - 8080
      - 4444
      - 1337

  registry:
    enabled: false     # Disabled to reduce noise
    monitor_autostart: false
    track_security_settings: false
    scan_interval: 300
    paths:
      - "HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run"
      - "HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\RunOnce"
      - "HKCU\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run"

  memory:
    enabled: false     # Disabled to reduce system impact
    scan_interval: 900
    threat_threshold: 0.8
    max_processes: 10

  behavior:
    enabled: false     # Disabled to reduce noise and system impact
    analysis_interval: 300
    threat_threshold: 0.9
    data_retention: 6

yara:
  enabled: true
  auto_update: false
  update_interval: "24h"
  rules_source: https://github.com/Yara-Rules/rules/archive/master.zip
  categories:              # Focused on essential categories only
    - malware
    - maldocs
    - webshells
  max_scan_threads: 1      # Reduced to minimize system impact
  scan_timeout: 20         # Increased timeout for complex rules
  rules_path: yara-rules
  max_file_size: "100MB"   # Increased for better coverage
  
  # Enhanced suppression settings
  suppress_environmental: true      # New: suppress environmental detections
  suppress_development_paths: true  # New: suppress detections in dev paths
  escalating_suppression: true      # New: escalating duplicate suppression

response:
  notification_settings:
    toast_enabled: true
    system_tray_enabled: true
    desktop_alert_enabled: true
    sound_enabled: false     # Disabled to reduce noise
    timeout_seconds: 3       # Reduced timeout for faster dismissal

  severity_thresholds:
    show_user_alerts: 4      # Only show high severity alerts
    auto_quarantine: 5       # Only quarantine critical threats
    block_execution: 5       # Only block critical threats

  user_interaction:
    allow_user_override: true
    require_admin_for_allow: true
    timeout_seconds: 30

  customization:
    company_branding: false
    custom_messages: false
    language: "en"

  # Enhanced notification settings
  notification_retry_count: 2       # New: retry failed notifications
  notification_timeout: 8           # New: notification display timeout
  duplicate_suppression: 120        # New: suppress duplicates for 2 minutes
  escalating_suppression: true      # New: escalating suppression

logging:
  level: "info"            # Keep info level for important events
  format: "text"           # Text format is more readable
  file_path: "agent.log"
  max_size: "50MB"         # Increased log size
  max_files: 3             # New: keep 3 log files
  compress: true           # New: compress old logs

# New: Performance tuning section
performance:
  max_memory_usage: "512MB"        # Memory limit
  cpu_limit_percent: 20            # CPU usage limit
  scan_queue_size: 100             # Scan queue limit
  event_queue_size: 1000           # Event queue limit
  cleanup_interval: 900            # Cleanup every 15 minutes
  
# New: Enhanced suppression rules
suppression:
  rules:
    - type: "path_contains"
      values: 
        - "\\AgentWindows\\"
        - "\\internal\\"
        - "\\go\\src\\"
        - "\\node_modules\\"
        - "\\.git\\"
        - "\\cursor\\user\\workspacestorage\\"
      reason: "development_path"
      
    - type: "rule_name_contains"
      values:
        - "powershell"
        - "debuggercheck"
        - "vmdetect"
        - "anti_dbg"
        - "capabilities"
      paths:
        - "C:\\Windows\\"
        - "C:\\Program Files\\"
        - "*\\AgentWindows\\*"
      reason: "environmental_system_path"
      
    - type: "file_extension"
      values:
        - ".go"
        - ".js"
        - ".ts"
        - ".json"
        - ".yaml"
        - ".yml"
        - ".md"
        - ".txt"
        - ".log"
      reason: "source_code_file"