# Safe EDR Agent Configuration
# This configuration is designed to prevent system freezes and minimize system impact

server:
  url: "http://192.168.20.85:5000"
  api_key: "f93ac1d1d7b64f07bd32c81e6ab8423e4cb7631f2051c9d8a2d340c5be3a4a9e"
  auth_token: "edr_system_auth_2025"
  timeout: 30
  retry_count: 2
  tls_verify: false

agent:
  id: ""
  name: "edr-agent-windows-safe"
  heartbeat_interval: 300    # Increased to reduce server traffic
  event_batch_size: 50       # Reduced batch size
  max_queue_size: 500        # Reduced queue size to prevent memory issues

monitoring:
  file_system:
    enabled: false            # Disabled by default for safety
    paths: []                 # Empty paths to prevent system monitoring
    recursive: false
    real_time_scan: false
    max_file_size: "10MB"     # Reduced file size limit
    exclude_extensions:
      - ".tmp"
      - ".log"
      - ".bak"
      - ".cache"
      - ".db"
      - ".sqlite"
      - ".etl"
      - ".evtx"
      - ".lock"
      - ".crdownload"
      - ".partial"
    exclude_paths:
      - "C:\\Windows\\*"
      - "C:\\Program Files\\*"
      - "C:\\Program Files (x86)\\*"
      - "C:\\ProgramData\\Microsoft\\Windows Defender\\*"
      - "C:\\Users\\*\\AppData\\Local\\Temp\\*"
      - "C:\\$Recycle.Bin\\*"
      - "C:\\System Volume Information\\*"
      - "C:\\Recovery\\*"
      - "*\\quarantine\\*"

  processes:
    enabled: false            # Disabled by default for safety
    scan_executables: false
    monitor_injections: false
    track_network_connections: false
    monitor_cmdline: false
    exclude_names:
      - "System"
      - "Idle"
      - "Registry"
      - "smss.exe"
      - "csrss.exe"
      - "wininit.exe"
      - "services.exe"
      - "lsass.exe"
      - "winlogon.exe"
      - "svchost.exe"
      - "dwm.exe"
      - "explorer.exe"
      - "taskmgr.exe"
      - "audiodg.exe"
      - "conhost.exe"
      - "fontdrvhost.exe"

  network:
    enabled: false            # Disabled to reduce system load
    monitor_dns: false
    block_malicious_ips: false
    capture_packets: false
    monitor_tcp: false
    monitor_udp: false
    scan_interval: 300

  registry:
    enabled: false            # Disabled to reduce noise
    monitor_autostart: false
    track_security_settings: false
    scan_interval: 600

  memory:
    enabled: false            # Disabled to prevent system impact
    scan_interval: 1800
    threat_threshold: 0.9
    max_processes: 5

  behavior:
    enabled: false            # Disabled to reduce system impact
    analysis_interval: 600
    threat_threshold: 0.9
    data_retention: 2

yara:
  enabled: false              # Disabled by default for safety
  auto_update: false
  update_interval: "24h"
  rules_source: ""
  categories: []
  max_scan_threads: 1         # Single thread to prevent overload
  scan_timeout: 10            # Reduced timeout
  rules_path: "yara-rules"
  max_file_size: "10MB"       # Reduced file size limit

response:
  notification_settings:
    toast_enabled: true
    system_tray_enabled: true
    desktop_alert_enabled: false  # Disabled to prevent UI freezes
    sound_enabled: false
    timeout_seconds: 5

  severity_thresholds:
    show_user_alerts: 5         # Only show critical alerts
    auto_quarantine: 6          # Disabled (no auto-quarantine)
    block_execution: 6          # Disabled (no auto-blocking)

  user_interaction:
    allow_user_override: true
    require_admin_for_allow: false
    timeout_seconds: 15

  customization:
    company_branding: false
    custom_messages: false
    language: "en"

logging:
  level: "info"
  format: "text"
  file_path: "agent.log"
  max_size: "10MB"
  max_files: 2
  compress: true

# Performance tuning to prevent system overload
performance:
  max_memory_usage: "128MB"      # Reduced memory limit
  cpu_limit_percent: 10         # Reduced CPU usage limit
  scan_queue_size: 20           # Reduced queue size
  event_queue_size: 100         # Reduced event queue
  cleanup_interval: 1800        # Cleanup every 30 minutes

# Enhanced suppression rules to prevent noise
suppression:
  rules:
    - type: "path_contains"
      values: 
        - "\\Windows\\"
        - "\\Program Files\\"
        - "\\Program Files (x86)\\"
        - "\\ProgramData\\Microsoft\\Windows Defender\\"
        - "\\$Recycle.Bin\\"
        - "\\System Volume Information\\"
        - "\\Recovery\\"
        - "\\quarantine\\"
        - "\\edr-agent"
      reason: "system_path"
      
    - type: "rule_name_contains"
      values:
        - "powershell"
        - "debuggercheck"
        - "vmdetect"
        - "anti_dbg"
        - "capabilities"
        - "environmental"
      reason: "environmental_detection"
      
    - type: "file_extension"
      values:
        - ".tmp"
        - ".log"
        - ".bak" 
        - ".cache"
        - ".db"
        - ".sqlite"
        - ".lock"
      reason: "temporary_file"

# Safe mode settings
safe_mode:
  enabled: true
  max_file_monitors: 1
  max_process_monitors: 1
  disable_real_time: true
  reduce_scanning: true
  minimal_logging: true